### ISSUE TITLE
Simple-todos 4, overloaded "text"

### ISSUE THREAD

**Issue by gingerbooth** [meteor/simple-todos#11]
On step 4 of the simple-todos tutorial (which is generally wonderful), I request that you rename the input field something other than "text". The number of things here called "text" obscures what's really going on. Pretty please. 

In fact, it would be good to not only complete de-overload "text", but also be sensitive to the similarity of the words "text" and "task". Imagine debugging (or reading) a program with variables "text", "test", "task", "tosk", and "tosl". You really slow down reading that...

**Comment by stubailo** [comment]
100% agree, as soon as I'm done with Windows I'll get to improving the tutorial.

**Comment by viktorsmari** [comment]
I agree, I also got confused running the tutorial.

**Comment by tmeasday** [comment]
The input field edits the "text" field on the tutorial, so it's sensible that it's called "text" also. It's pretty standard practice to name inputs the same things as the document field they edit.

Maybe there's an argument that we should rename it from `task.text` to `task.body` or something. I can see the argument but honestly it seems a bit bikesheddy @stubailo.

**Comment by stubailo** [comment]
Yeah I agree this isn't critical.
