### ISSUE TITLE
simple-todos 6, cannot deploy

### ISSUE THREAD

**Issue by gingerbooth** [meteor/simple-todos#12]
Step 6 doesn't work to deploy an application to meteor.com. "Sorry, that site belongs to another user." More verbiage needed.

**Comment by stubailo** [comment]
Ah yes we should mention that you need to pick a unique name. Thanks for the feedback! Not many people give me feedback about the tutorial, it's very helpful.

**Comment by gingerbooth** [comment]
OK, picked a probably-unique name. And got... this. 

![installtodoonmeteor](https://cloud.githubusercontent.com/assets/6087993/6854897/7c83aa30-d3ca-11e4-9331-7a0ba5fd6c29.png)

**Comment by ddddave** [comment]
I had the same issue. I was able to resolve by renaming the folder in my home directory from "simple-todos" to something unique. Maybe you could try changing "Users\Ginger\simple-todos" to "Users\Ginger\gingertodo" then try to deploy using "meteor deploy gingertodo.meteor." Make sure you change directories to "Users\Ginger\gingertodo" so you are deploying from there.

**Comment by stubailo** [comment]
I think this should be resolved now? In any case, this would be an issue for https://github.com/meteor/meteor
