### ISSUE TITLE
simple-todos 9, username_only

### ISSUE THREAD

**Issue by gingerbooth** [meteor/simple-todos#13]
This may be perfectly correct, but I was kinda expecting "USERNAME_ONLY" to not request a password on the login form. There is a password field on the login form.

Accounts.ui.config({
  passwordSignupFields: "USERNAME_ONLY"
});

Later, there's also this reference to "Spacebars":

Finally, add a Spacebars statement to display the username field on each task right before the text:
<span class="text"><strong>{{username}}</strong> - {{text}}</span>

**Comment by stubailo** [comment]
This should be an issue on https://github.com/meteor/meteor about the accounts package; the tutorial is not really the problem.

I'll also include an explanation of what spacebars does in the next version.
