### ISSUE TITLE
meteor mongo in TODO 3

### ISSUE THREAD

**Issue by pandeysoni** [meteor/simple-todos#15]
Started mongo console using <meteor mongo> command and after that just write insert command but it didn't show anything then again i wrote same command then it shows inserted, so my concern is why it was not worked for first time when i wrote meteor mongo console and run insert command.
![meteor mongo1](https://cloud.githubusercontent.com/assets/7939709/6936781/523d7c1c-d873-11e4-8ca8-67d54aaf90ce.JPG)

**Comment by stubailo** [comment]
Sorry, I don't know the answer - if this happens to you a lot you should file a bug on Meteor itself here: https://github.com/meteor/meteor
