### ISSUE TITLE
simple-todo 9 custom fields on signup

### ISSUE THREAD

**Issue by pandeysoni** [meteor/simple-todos#16]
It is very easy to make signup and login using accounts-ui and accounts-password package, but i am not able to add more custom field in signup page. Any idea how to make custom fields exclude username.

Thanks

**Comment by jeanmatheussouto** [comment]
Hi @pandeysoni take a look on https://github.com/meteor/meteor/blob/270217b5660bc5c2ef6aa96ac7a9a5dc00591830/packages/accounts-ui-unstyled/accounts_ui.js#L34 to more details, hope this helps!

**Comment by stubailo** [comment]
Hi, this is more of a question for [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/). Good luck!
