### ISSUE TITLE
Link to simple-todos.css in Meteor Tutorial is wrong.

### ISSUE THREAD

**Issue by kaona** [meteor/simple-todos#20]
The link at https://www.meteor.com/try for simple-todos.css is : https://github.com/meteor/simple-todos/blob/377a8610c2fa77056d015e6998d5eb894436c99e/simple-todos.css

I believe the intended link is: https://github.com/meteor/simple-todos/blob/master/simple-todos.css

Running the tutorial on the empty css file the original download comes with returned the following in the terminal:
***
=> Your application has errors. Waiting for file change.
=> Modified -- restarting.
=> Errors prevented startup:                  
   
   While building the application:
   simple-todos.css: property missing ':' near line 3:6
***
Yes? No?

**Comment by stubailo** [comment]
Interesting - the file I intended to link to is the one that is automatically generated by `meteor create`. What caused the error on line 3? Initially there are supposed to be no declarations in the CSS file and you add them in [step 2](https://www.meteor.com/try/2).

**Comment by kaona** [comment]
I dont know. Didnt work for me until i added the part 2 .js.

**Comment by kaona** [comment]
I dont remember now. Will better document next time. Thank you.
