### ISSUE TITLE
Tutorial 9 does not display user who created the task

### ISSUE THREAD

**Issue by dpneumo** [meteor/simple-todos#22]
<span class="text"><strong>{{username}}</strong> - {{text}}</span>

should be

<span class="text"><strong>{{userName}}</strong> - {{text}}</span>

However, after removing insecure and adding the Meteor methods in tutorial 10, the {{username}} form is correct.

**Comment by metaprinter** [comment]
in step 9 shows username all lowercase in the html and js file for me. I'm not seeing this error.

**Comment by stubailo** [comment]
Yeah, the all-lowercase form is definitely correct.
