### ISSUE TITLE
splitting simple-todos.js in to server and client folder

### ISSUE THREAD

**Issue by grinono** [meteor/simple-todos#24]
Somehow when splitting this Example code into client and server subfolders. i got error of method not defined. do i need to run the methods on the client as well? or place the methods is a run both folder or something?

/client/taskClient.js

 Template.body.helpers({
    tasks: function () {
      if (Session.get("hideCompleted")) {
        // If hide completed is checked, filter tasks
        return Tasks.find({checked: {$ne: true}}, {sort: {createdAt: -1}});
      } else {
        // Otherwise, return all of the tasks
        return Tasks.find({}, {sort: {createdAt: -1}});
      }
    },
    hideCompleted: function () {
      return Session.get("hideCompleted");
    },
    incompleteCount: function () {
      return Tasks.find({checked: {$ne: true}}).count();
    }
  });

  Template.body.events({
    "submit .new-task": function (event) {
      // This function is called when the new task form is submitted
      var text = event.target.text.value;

      Meteor.call("addTask", text);

      // Clear form
      event.target.text.value = "";

      // Prevent default form submit
      return false;
    },
    "change .hide-completed input": function (event) {
      Session.set("hideCompleted", event.target.checked);
    }
  });

  Template.task.events({
    "click .toggle-checked": function () {
      // Set the checked property to the opposite of its current value
      Meteor.call("setChecked", this._id, ! this.checked);
    },
    "click .delete": function () {
      Meteor.call("deleteTask", this._id);
    }
  });

  Accounts.ui.config({
    passwordSignupFields: "USERNAME_ONLY"
  });

/server/taskServer.js

Tasks = new Mongo.Collection("tasks");

Meteor.methods({
  addTask: function (text) {
    // Make sure the user is logged in before inserting a task
    if (! Meteor.userId()) {
      throw new Meteor.Error("not-authorized");
    }

    Tasks.insert({
      text: text,
      createdAt: new Date(),
      owner: Meteor.userId(),
      username: Meteor.user().username
    });
  },
  deleteTask: function (taskId) {
    Tasks.remove(taskId);
  },
  setChecked: function (taskId, setChecked) {
    Tasks.update(taskId, { $set: { checked: setChecked} });
  }
});

**Comment by stubailo** [comment]
It's a little hard to tell because of the code formatting (I would suggest uploading a repo to GitHub next time) but I think the problem is that `Tasks = new Mongo.Collection("tasks");` needs to be defined on client and server.

In general, you should also define your methods on both client and server to get optimistic UI: http://info.meteor.com/blog/optimistic-ui-with-meteor-latency-compensation
