### ISSUE TITLE
one page

### ISSUE THREAD

**Issue by xavierartot** [meteor/simple-todos#25]
Can I have the tutorial in one page.
Thanks

**Comment by stubailo** [comment]
Is this for printing purposes, or other? Just curious.

**Comment by xavierartot** [comment]
It's for Kindle

**Comment by xavierartot** [comment]
I mean I'd like to save a site to kindle I'm using a chrome's plugin for that.

**Comment by stubailo** [comment]
Interesting. Right now this isn't a top priority, but I'll keep it in mind if an opportunity arises.

**Comment by xavierartot** [comment]
extension: http://dotepub.com/
