### ISSUE TITLE
What's the Purpose of hideCompleted()?

### ISSUE THREAD

**Issue by mikeborozdin** [meteor/simple-todos#36]
What is the purpose of the `hideCompleted` function()? 

``` js
hideCompleted: function () {
  return Session.get("hideCompleted");
}
```

Which is used in the template:

``` js
<input type="checkbox" checked="{{hideCompleted}}" />
```

There doesn't seem to be any need in it. A checkbox becomes checked when a user presses on it. And if you refresh the page, the contents of the `Session` object will be gone anyway.

Having that function and using it in the template makes it a confusing tutorial, as it has things which are not necessary.

**Comment by stubailo** [comment]
Yes, that is correct! It's unnecessary for a checkbox.

**Comment by kvetoslavnovak** [comment]
I had the very same question and suspicion :-)

**Comment by tmeasday** [comment]
If you edit the code, it'll load the old state from the Session, so it's not totally unnecessary. However we're moving away from the session anyway, so I guess I should get rid of it.

**Comment by stubailo** [comment]
@tmeasday named reactive dicts still preserve state. so the point might be valid.

**Comment by tmeasday** [comment]
@stubailo yes but we don't recommend naming reactive dicts for template instance state for some reason that escapes me right now. I think it has some edge cases that makes it super confusing.
