### ISSUE TITLE
Newly added todo items are hidden by the "Hide Completed" checkbox

### ISSUE THREAD

**Issue by steven-wolfman** [meteor/simple-todos#38]
To repro: Work through the end of step 8. Uncheck Hide Completed (not necessary, but easier to follow). Add a new task. Check Hide Completed, and watch it disappear.

This is because newly inserted tasks have no checked field (from Step 4.2).

Suggested fixes: 

 - Update the Tasks.insert line to include checked: false on insertion in ~Step 5.3 and explain the reason why there.
 - Do the update instead between 8.4 and 8.5 by pointing out the bug (and perhaps mentioning again that there's no fixed schema).

Hope this helps. Thanks for the tutorial! I'd create a pull request, but I've no idea how you set up the step commits as you did without painful and extended manipulation. :)

**Comment by steven-wolfman** [comment]
Ack. My fault. Your {$ne: true} filter catches this just fine and maintains backwards compatibility with the "schema" when there was no checked option.

**Comment by stubailo** [comment]
Yeah, I guess you did `false` instead. It's a bit of a hack, I guess!
