### ISSUE TITLE
Simple-todos Chapter 10

### ISSUE THREAD

**Issue by jtryan** [meteor/simple-todos#4]
While running the app, I noticed that even if a person was not logged in, they could still mark a task as complete and delete it. I believe the check for the user being logged in is only applying to the addtask method. For an inelegant soluton I added the check to the other two methods, 'deleteTask' and 'setChecked'. This works to stop someone from altering taks when they are not logged in.

```javascript
  deleteTask: function (taskId) {
    // Make sure the user is logged in before inserting a task
    if (! Meteor.userId()) {
      throw new Meteor.Error("not-authorized");
    }

    Tasks.remove(taskId);
  },
  setChecked: function (taskId, setChecked) {
    // Make sure the user is logged in before inserting a task
    if (! Meteor.userId()) {
      throw new Meteor.Error("not-authorized");
    }

    Tasks.update(taskId, { $set: { checked: setChecked} });
  }
```

**Comment by stubailo** [comment]
I'm going to make this change in the next version of the tutorial. I just built a whole lot of infrastructure to make things easier to update; sorry it has taken so long.

**Comment by tmeasday** [comment]
I think it's fair to say:

```
if ((! Meteor.userId()) || (task.private && task.owner !== Meteor.userId())) {...
```

Is redundant. What's wrong with a logged out user deleting a public task? That seems OK to me. If it's  a private task, then the last check will definitely fail if you are logged out.

I think it's fine.
