### ISSUE TITLE
Task default private value on addTask

### ISSUE THREAD

**Issue by mrisoli** [meteor/simple-todos#43]
Shouldn't the task private attribute be set to true on addTask?

This has little to do with the tutorial itself, but logically speaking, if there's no option to set the task visibility on the new task form, shouldn't it default to being private?

I mean, if a task is public one can simply 'publish' it by toggling the correspondent button(if the default value is true).
Currently, if a task is supposed to be private it is exposed to everyone on creation until a user makes it private, and that is a privacy concern.

**Comment by stubailo** [comment]
I think some concessions need to be made for a tutorial to make sense as a sequential series of steps - this was the smoothest transition from no privacy to privacy; did you find it easy to add that feature yourself afterwards?
