### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Kamin12** [meteor/simple-todos#44]
Can this be updated to show the code from the example in the Meteor Guide?

**Comment by stubailo** [comment]
We're working on overhauling the example system for Meteor 1.3. As much as possible, the new examples will follow Guide recommendations.

**Comment by Kamin12** [comment]
Cool, thanks for the good work.

**Comment by tmeasday** [comment]
It's happening 1.3-tutorial.meteorapp.com

**Comment by Kamin12** [comment]
Am I missing something? I was referring to the Todos apps with lists, and template names such as "Lists_show_page", and "Lists_Show", and helpers such as todoArgs and ListArgs...All that good stuff that is covered in the Meteor Guide. What you pointed me to shows the very basic todos covered in the tutorial.

**Comment by Kamin12** [comment]
This should not have been closed. You guys need to pay more attention to
the issues in the Guide. It's almost beginning to look like false
advertisement.

On Thu, Mar 17, 2016 at 5:23 PM, Tom Coleman <notifications@github.com>
wrote:

> Closed #44 <https://github.com/meteor/simple-todos/issues/44>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/meteor/simple-todos/issues/44#event-594241951>
>



-- 
Ari Kamin
Founder, Wread Wrkr

**Comment by stubailo** [comment]
@Kamin12 I think you're looking for this app: https://github.com/meteor/todos
