### ISSUE TITLE
List.todos

### ISSUE THREAD

**Issue by Kamin12** [meteor/simple-todos#45]
This issue is for the Meteor Guide. 

There doesn't seem to be a 'List.todos' publication defined in the guide, although it is subscribed to from Template.Lists_show-page.onCreated.

Can you share the code for that publication? Include it in a comment or edit it into the guide? Would be extremely helpful.

**Comment by tmeasday** [comment]
Hi @Kamin12  - you can open guide related issues at https://github.com/meteor/guide/issues

In this case, the examples in the guide are taken from the todos app, which is at https://github.com/meteor/todos

**Comment by Kamin12** [comment]
The examples in the guide are not taken from that repo. This issue shouldn't be closed.
