### ISSUE TITLE
simple-todo 2.3, find module doesn't find a file on win10

### ISSUE THREAD

**Issue by spawn-guy** [meteor/simple-todos#47]
Started following TODO tutorial in React - all goes fine. but then restarted the tutorial with Blaze

```
W20160412-14:28:32.458(2)? (STDERR) C:\Users\paul\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
W20160412-14:28:32.458(2)? (STDERR)                         throw(ex);
W20160412-14:28:32.458(2)? (STDERR)                               ^
W20160412-14:28:32.458(2)? (STDERR) Error: Cannot find module './body.html'
W20160412-14:28:32.458(2)? (STDERR)     at require (packages\modules-runtime.js:95:19)
W20160412-14:28:32.459(2)? (STDERR)     at meteorInstall.imports.ui.body.js (imports/ui/body.js:5:1)
W20160412-14:28:32.459(2)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:158:9)
W20160412-14:28:32.459(2)? (STDERR)     at require (packages\modules-runtime.js:92:16)
```

the File is here. i can navigate to it through ctrl+clicking in phpStorm.

I am on Windows 10 x64. meteor is started within phpStorm 2016.1 x64.

and, Yes, i do get that this error is.. hmm.. quite ridiculous. so i'd like to figure "why?" and "how to fix it?".

**Comment by VeritasCZ** [comment]
Try 
`'../body.html';`

**Comment by stubailo** [comment]
In the tutorial, there are links to what the code should look like at every step. I'd suggest clicking the link in the code snippet box and seeing how your project is different from that commit.

**Comment by spawn-guy** [comment]
@VeritasCZ i did try that. even `import '../ui/body.html';`

here is how it looks like in the ... image format
![image](https://cloud.githubusercontent.com/assets/1442562/14486958/1fc9e920-0160-11e6-985a-20c26d6d08bb.png)

I created a project yesterday. and did finish the React tutorial successfully

**Comment by spawn-guy** [comment]
an update. may be unrelated, but may be related.

i've been deploying an meteor 1.3.1 app. with demeteorizer. i used some code from the full featured "todo" app. and it uses "faker" as an npm module.

well,... running this code just failed. node was looking for "./lib" module, that is missing. the reference went from faker lib. i removed faker from npm/node dependencies and commented faker-related code out. and voila it works!

_may it be_ that there is a problem with node/npm and imports that start with a dot?

**Comment by ModusVivendi** [comment]
I'm having the same issue but on an ubuntu container on Cloud9 IDE.  Exactly the same.  I get to step 2.4 and try to import the body.js file in imports/ui and receive an error from import/ui/body.js that it cant find the import/ui/body.html file.  My code is exactly the same as is on the github project.  

I'm also not quite sure I understand @spawn-guy fix mentioned above, so I'm stuck as it is.

**Comment by spawn-guy** [comment]
Try deleting node_modules folder. A couple of times I had problem with not fully downloaded npm modules. On my local pc and on CircleCI. Also npm cache folder(not sure where it is). This _may_ help, but I still have no clue what is wrong

**Comment by ModusVivendi** [comment]
I got mine working by just starting up a cloud9 workspace that did not have anything pre-installed related to meteor.  Previously I had tried this using the cloud9 meteor starting container, but there must be something preinstalled of an incompatible version.

**Comment by bwoods89** [comment]
I just had this same problem, and what had happened was that I had replaced the contents of server/main.js with the one import line listed in instruction 2.4 rather than the contents of client/main.js.
