### ISSUE TITLE
Security does not work - un-logged-in user can check off and delete tasks

### ISSUE THREAD

**Issue by deborah-ufw** [meteor/simple-todos#48]
I was going through the Meteor tutorial steps to build the to-do app and noticed that the security did not work - after logging out, I could still check off and delete tasks. 

To make sure I had not made a mistake in following the tutorial, I downloaded a zip of this repository, compiled it, updated Meteor (to current version 1.3.2) and tested it. After creating my account, creating some tasks, and logging out, I was still able to check off and delete tasks without being logged in.

I'm not familiar enough yet with Meteor to identify the problem, but wanted to point out that it's there.

**Comment by stubailo** [comment]
Yes, that's not the intention - the intent is just that logged out users can't make tasks, and they can't see or manipulate private tasks. You can add additional code to your methods to implement the rules you mentioned.
