### ISSUE TITLE
"Todos" tutorial text is wrong - says only task creator should be able to checkoff & delete, but any user can

### ISSUE THREAD

**Issue by deborah-ufw** [meteor/simple-todos#49]
This is related to this bug, which was closed: ["Security does not work - un-logged-in user can check off and delete tasks"](https://github.com/meteor/simple-todos/issues/48)

Stubailo closed the bug with comment that it is intended that user themselves complete security methods to make sure that only the correct logged-in user can check off and delete tasks they own.

However, the todos tutorial includes the statement [here](https://www.meteor.com/tutorials/blaze/publish-and-subscribe):
### In order to finish up our private task feature, we need to add checks to our deleteTask and set Checked methods to make sure only the task owner can delete or check off a private task:"

Code is included below this statement for user to paste into tasks.js. The code includes a "not-authorized" error for the app to throw, which never does get thrown.

This code does not accomplish what the text says it will accomplish. Any un-logged in user can check off and delete anybody's tasks. So if the code works as intended, then the verbiage in the tutorial needs to be changed. (I think the code does not work as intended.)

**Comment by stubailo** [comment]
> delete or check off a private task

Are we talking about all tasks here, or private tasks?

**Comment by deborah-ufw** [comment]
Oops. There is a note below the code on the tutorial explaining what Stubailo mentioned in his comment. However, since only logged-in user who owns the task can SEE the private task, the private task is already secure from check-off and deletion. This code is never used.

I think it would be useful to modify the tutorial so user can see this code work.

**Comment by deborah-ufw** [comment]
sorry, I missed the note in the tutorial that it was only protecting private tasks. I was expecting only logged in user to be able to check off/delete only their own tasks. My bad.

**Comment by stubailo** [comment]
The main point here is that hiding a button is not security - you need to have security at the method level. Maybe something to mention.
