### ISSUE TITLE
Step 3.3 Where is "your app directory"?

### ISSUE THREAD

**Issue by jfkquality** [meteor/simple-todos#52]
https://www.meteor.com/tutorials/blaze/collections, in Step 3.3 it says  "In a new terminal tab, go to your app directory and type:" Where is that directory? I'm using Windows 8.1.

**Comment by aisamu** [comment]
In Step 1.1 you had to open your Command Prompt (cmd.exe) and run the command
```
  meteor create simple-todos
```
This created a folder named `simple-todos\` – your app directory – inside the folder where the command was run. 
If you didn't change the directory after opening the prompt, your app dir is probably `C:\Users\Your-User-Name\simple-todos`

**Comment by BrianMulhall** [comment]
the app directory is the directory that was created from the meteor create simple-todos command. This folder is the "root" directory for your app and it from that folder that meteor mongo should be run. hope that helps.
