### ISSUE TITLE
Documentation: section 2 - where is the imports directory

### ISSUE THREAD

**Issue by RTCeables** [meteor/simple-todos#54]
Section 1 of this tutorial (creating app) lists folders client and server only with associated files in each. Move onto section 2 (templates) and immediately thrown by this sentence "Then we create some new files in the imports/ directory:"

Where is this "imports" directory as it cannot be found in the projects folder. Should the documentation not be changed to say "then we first create an imports directory" or something to that effect.

**Comment by zimejin** [comment]
same problem here

**Comment by aisamu** [comment]
I mirrored the folder structure shown in the repository and it worked, so I guess it is safe to assume you're supposed to create it yourself. (manually, not by running some meteor command)

I agree with the brief mention in the tutorial, though.

**Comment by BrianMulhall** [comment]
We have added the following to the tutorial

Create a new directory with the name imports inside simple-todos folder. Then we create some new files in the imports/ directory:

To avoid any confusion, thanks for the input :)
