### ISSUE TITLE
Tasks inserted using the mongo console do not pass validation

### ISSUE THREAD

**Issue by aisamu** [meteor/simple-todos#55]
Section 3 suggests that we insert a few documents into the collection using the database console:

> Let's use the server database console to insert some documents into our collection. In a new terminal tab, go to your app directory and type:
> `meteor mongo`
> This opens a console into your app's local development database. Into the prompt, type:
> `db.tasks.insert({ text: "Hello world!", createdAt: new Date() });`
> [...] Insert a few more tasks from the database console with different text. In the next step, we'll see how to add functionality to our app's UI so that we can add tasks without using the database console.

Mongo's default type for  `_id` is `ObjectID`, whereas Meteor uses a plain `String`:

> https://docs.meteor.com/api/collections.html
> [...] The default id generation technique is 'STRING'.

This creates no issue until Section 9, when we start validating the parameters: 

``` JavaScript
'tasks.setChecked'(taskId, setChecked) {
   check(taskId, String);  //Fails for ObjectID
```

Methods called with "old" tasks return a `Match failed [400]` and do not run. We cannot check nor remove tasks created with the console. 
Tasks created with the web interface or the web console work correctly, which makes it even more confusing!

My instinct (no previous Meteor or Mongodb experience) was to inspect the offending task. After finding an `ObjectID` instead of a `String`, I promptly changed the methods to use the `._str` field of the given `taskId`. As you can imagine, old tasks began to work properly, but new tasks – with a plain `String` id – stopped working.

I guess running `meteor reset` somewhere in Section 9 would solve this and other potential hiccups [1], while also teaching about the very useful `reset` command! 

[1] - Tasks added before the Accounts functionality appear as "- taskDetails", which made me wonder whether there was an issue with the template.

**Comment by stemid** [comment]
I ran into the same confusion and ObjectId is apparently something from MongoDB so it could be hard for Meteor docs to keep up with whatever changes happen on that end.

Imo the easiest thing would be to add some more logic to your tasks methods.

```
    'tasks.remove'(taskId) {
        // A little workaround for items created directly in the meteor
        // mongo shell.
        if (taskId instanceof Object) {
            Tasks.remove({_id: taskId});
            return;
        }

        check(taskId, String);

        Tasks.remove(taskId);
    },
```

**Comment by vinceguerrero** [comment]
I just hit this myself as well.  It also affects tasks.setChecked.

@stemid  your suggestion worked for me, but returning early after removing via _id would negate anything that gets further added to the method, which does happen later in the tutorial.

I tried to just set taskId to taskId._str which at least gets the ids in a common form, but that causes "undefined" errors on the tasks entered from the mongo shell.

A new section on meteor reset, per @aisamu seems reasonable.  Better yet, a brief warning/explanation about the divergence that causes this would be a useful tip for beginners.

**Comment by stemid** [comment]
@vinceguerrero Yes well that's easily solved by using another variable for the task ID.

        if (taskId instanceof Object) {
            const _taskId = taskId.toString();
        } else {
            const _taskId = taskId
        }
        Tasks.remove(_taskId);

**Comment by vinceguerrero** [comment]
I still receive undefined errors on the mongo shell entries when doing that:

`Exception while simulating the effect of invoking 'tasks.remove' TypeError: Cannot read property 'private' of undefined`

But this makes sense; as you mentioned, mongo entries have ObjectId values and not strings, so normalizing the ID type on the FE isn't a good idea anyway.  And here I thought I had a clever solution.  D'oh!

```
db.tasks.find();
{ "_id" : ObjectId("591e3f55c6e256f1a677e3f4"), "text" : "This is a task from the mongo shell.", "createdAt" : ISODate("2017-05-19T00:41:56.999Z") }
{ "_id" : "4dc26Dj498EHpzNtx", "text" : "This is a task from the web interface.", "createdAt" : ISODate("2017-05-19T00:42:10.177Z"), "owner" : "iPor2yndQisNFhrwx", "username" : "foobar" }

```

If we want to preserve the methods' total functionality (as in, not returning early), the best "fix" seems to be to remove the ```check(taskId, String);``` line entirely, but that's probably not useful for the purpose of this tutorial.  This could be a handy note somewhere though.  I'm sure we're not the only people who got thrown for a loop on this.

**Comment by vinceguerrero** [comment]
I still receive undefined errors on the mongo shell entries when doing that:

`Exception while simulating the effect of invoking 'tasks.remove' TypeError: Cannot read property 'private' of undefined`

But this makes sense; as you guys mentioned, mongo entries have ObjectId values and not strings, so normalizing the ID type on the FE isn't a good idea anyway.  And here I thought I had a clever solution.  D'oh!

If we want to preserve the methods' total functionality (as in, not returning early), the best "fix" seems to be to remove the ```check(taskId, String);``` line entirely, but that's probably not useful for the purpose of this tutorial.  This could be a handy note somewhere though.  I'm sure we're not the only people who got thrown for a loop on this.
