### ISSUE TITLE
instance is not defined, 7.4  Add event handler for checkbox

### ISSUE THREAD

**Issue by bewam** [meteor/simple-todos#56]
Thanks for your tut.

METEOR@1.4.1.2

If I've known Meteor, I didn't do this tutorial. So I can't explain why It does that.
With chromium, I obtain: 

> Uncaught TypeError: Cannot read property 'state' of null  |  body.js:42

and with Firefox:

> TypeError: instance is null | app.js:155:13

with meteor@099e720bdef9264fb4a50c96aff01cb776c61d58

To solve it, I had to get the "instance" variable from the third argument, like:

``` javascript
'change .hide-completed input' (event, nothing, instance) {
        instance.state.set('hideCompleted', event.target.checked);
    },
```

And the checkbox works as expected.

I don't know if I did something wrong. In that case, can someone explain?

**Comment by gautam-dey** [comment]
There is a problem in the checkbox its not working properly.

So, I fixed it by removing the input @ line no. 38 in the above code and it works fine.

**Comment by BrianMulhall** [comment]
This is no longer an issue in Meteor 1.10.1. The code in Step 7.4 works as expected.
