### ISSUE TITLE
Storing temporary UI state in a Reactive Dictionary don't work

### ISSUE THREAD

**Issue by kenn44** [meteor/simple-todos#61]
Hello,

I am following the default tutorial and I am stuck here: [Step7: Storing temporary UI state in a Reactive Dictionary](https://www.meteor.com/tutorials/blaze/temporary-ui-state)

As soon as I insert the `import { ReactiveDict } from 'meteor/reactive-dict';`
, the application no longer displays the body. it only displays the gradient in the background.
Although I continue the tutorial it does not work out.

**Comment by jankapunkt** [comment]
Have you added the reactive dict before? --> `meteor add reactive-dict`?

**Comment by BrianMulhall** [comment]
I am going to close this as it cant be reproduced and the likely cause can be fixed by the suggestion offered
