### ISSUE TITLE
Adding incompleteCount to page title

### ISSUE THREAD

**Issue by athyuttamre** [meteor/simple-todos#9]
Sorry if this isn't the best place to ask for help, but I would greatly appreciate your help on something I'm trying.

My attempt is to also show the incompleteCount in the page title. I tried adding `{{incompleteCount}}` to the `title` tag, but unfortunately that doesn't seem to work. Instead the page title simply says "Todo List ({{incompleteCount}})".

I figured the problem must be that the helper is only defined on the `body` template. I correspondingly added it to the head template, but that didn't work either.

What's the best way to achieve this?

```
<head>
    <title>Todo List ({{incompleteCount}})</title>
</head>
```

```
Template.head.helpers({
    incompleteCount: function () {
        return Tasks.find({checked: {$ne: true}}).count();
    }
});
```

**Comment by stubailo** [comment]
Hey. Unfortunately, Meteor doesn't currently support reactivity in the `<head>` section of the page.

If you want to change the title, you can do it using [`Tracker.autorun`](http://docs.meteor.com/#/basic/Tracker-autorun), like so:

```
Tracker.autorun(function () {
  window.title = "Todo List (" + Tasks.find({checked: {$ne: true}}).count() + ")";
});
```

**Comment by athyuttamre** [comment]
That works, thanks @stubailo! Is reactivity in `<head>` on the timeline?

**Comment by stubailo** [comment]
Currently it's not, and I can think of at least one good reason - lots of search engines and sharing services use the `<head>` to collect metadata about the page, so we definitely want that to be served by the server. Currently we don't have default support for server-side rendering, so I think having `<head>` always be static is a good compromise.

Also, there are only a few things in the `<head>` that you would want to be reactive, and those aren't that hard to set - like the `title`.
